while True:
    import turtle
    turtle.Screen().bgcolor("White")
    x = turtle.Turtle()
    x.pensize(20) #Thickness of marker (20 to 30 range is good)
    x.shapesize(4) #Size of marker on screen
    x.right(0) #Initial direction of marker (55) for nazi swastika and 0 for indian swastika
    x.forward(100)
    x.right(90)
    x.forward(100)
    x.penup()
    x.right(180)
    x.forward(100)
    x.left(90)
    x.forward(100)
    x.pendown()
    x.right(90)
    x.forward(100)
    x.right(90)
    x.forward(100)
    x.penup()
    x.right(180)
    x.forward(100)
    x.left(90)
    x.forward(100)
    x.pendown()
    x.right(90)
    x.forward(100)
    x.right(90)
    x.forward(100)
    x.penup()
    x.right(180)
    x.forward(100)
    x.left(90)
    x.forward(100)
    x.pendown()
    x.right(90)
    x.forward(100)
    x.right(90)
    x.forward(100)
    x.penup()
    x.right(180)
    x.forward(100)
    x.left(90)
    x.forward(100)
    x.pendown()
    #FOLLOWING MAKES IT AN INDIAN SWASTIKA FOR DOTS
    x.penup()
    x.forward(50)
    x.right(90)
    x.forward(50)
    x.pendown()
    x.forward(1)
    x.penup()
    x.right(180)
    x.forward(1)
    x.forward(100)
    x.pendown()
    x.forward(1)
    x.penup()
    x.right(180)
    x.forward(1)
    x.forward(50)
    x.right(90)
    x.forward(100)
    x.left(90)
    x.forward(50)
    x.pendown()
    x.forward(1)
    x.penup()
    x.right(180)
    x.forward(1)
    x.forward(100)
    x.pendown()
    x.forward(1)
    x.penup()
    x.shapesize(0.00001) #Makes marker invisible
    x.reset() # make the whole thing a comment if you want it to now clear the screen after each drawing
    x.shapesize(0.00001)
    #turtle.done() #IF YOU WANT TO STOP THE LOOP AFTER ONE DRAWING